# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceip',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
