# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceip', '0002_auto_20180929_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traceip',
            old_name='ip',
            new_name='request_by_ip',
        ),
        migrations.AddField(
            model_name='traceip',
            name='searched_for_ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
